# Generated by Django 3.0.14 on 2022-09-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrorentapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adduser',
            name='adhar',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
    ]
