# Generated by Django 3.0.14 on 2022-10-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrorentapp', '0002_adduser_adhar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adduser',
            name='adhar',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
