# Generated by Django 3.0.14 on 2022-10-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrorentapp', '0003_auto_20221005_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('tool_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=30)),
                ('tool_spec_1', models.CharField(blank=True, max_length=200)),
                ('tool_spec_2', models.CharField(blank=True, max_length=200)),
                ('tool_info', models.TextField(blank=True)),
                ('book_price', models.CharField(max_length=9)),
                ('tool_type', models.CharField(blank=True, max_length=200)),
                ('tool_photo', models.ImageField(upload_to=None)),
            ],
        ),
    ]
