# Generated by Django 3.0.14 on 2022-10-05 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrorentapp', '0004_tools'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('booking_amt_paid', models.CharField(max_length=12)),
                ('rented_to', models.CharField(max_length=50)),
                ('owner_name', models.CharField(max_length=50)),
                ('request_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('tool_id', models.CharField(max_length=20)),
                ('is_booked', models.BooleanField(default=False)),
                ('required_from', models.DateTimeField(blank=True)),
                ('required_till', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('request_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('send_to', models.CharField(max_length=50)),
                ('send_from', models.CharField(max_length=50)),
                ('request_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('tool_id', models.CharField(max_length=20)),
                ('is_accepted', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('required_from', models.DateTimeField(blank=True)),
                ('required_till', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='tools',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='tools',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
