# Generated by Django 3.0.14 on 2022-10-05 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agrorentapp', '0005_auto_20221005_2006'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tools',
            new_name='Tool',
        ),
    ]
