# Generated by Django 3.0.14 on 2022-10-06 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agrorentapp', '0007_auto_20221005_2041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tool',
            old_name='book_price',
            new_name='rent_price',
        ),
    ]
