# Generated by Django 3.0.14 on 2022-10-29 17:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrorentapp', '0009_auto_20221013_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='request_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 29, 23, 21, 18)),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 29, 23, 21, 18)),
        ),
    ]
