# Generated by Django 3.0.14 on 2022-10-31 04:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrorentapp', '0011_auto_20221030_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='request_time',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 31, 9, 34, 50)),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 31, 9, 34, 50)),
        ),
    ]
