# Generated by Django 3.0.14 on 2022-10-31 04:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrorentapp', '0012_auto_20221031_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 31, 9, 35, 21)),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 31, 9, 35, 21)),
        ),
    ]
