# Generated by Django 3.0.14 on 2022-10-31 04:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrorentapp', '0014_auto_20221031_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 31, 10, 15, 52)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='required_from',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='booking',
            name='required_till',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 31, 10, 15, 52)),
        ),
    ]
