# Generated by Django 3.0.14 on 2022-11-04 18:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrorentapp', '0015_auto_20221031_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 4, 23, 50, 22)),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 4, 23, 50, 22)),
        ),
    ]
