# Generated by Django 3.0.14 on 2022-11-25 16:41

import agrorentapp.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrorentapp', '0016_auto_20221104_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 25, 22, 11, 26)),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 25, 22, 11, 26)),
        ),
        migrations.AlterField(
            model_name='tool',
            name='location',
            field=agrorentapp.models.locationField(blank=True, max_length=200),
        ),
    ]
